//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaManager.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CD
    {
        public CD()
        {
            this.Tracks = new HashSet<Track>();
        }
    
        public int ID { get; set; }
        public string Artisit { get; set; }
    
        public virtual ICollection<Track> Tracks { get; set; }
    }
}
